url: https://scaleway.github.io
baseurl: /cloud-courses
title: cloud-courses by Scaleway
author: Rémy Léone
exclude: [".vagrant", ".terraform"]
repository: scaleway/cloud-courses
plugins:
  - jekyll-sitemap
